### ISSUE TITLE
Problem with adrenaline

### ISSUE THREAD

**Issue by DnBass** [cy33hc/vita-launcher#10]
Followed your video on how to boot to adrenaline from the launcher. When I click something to boot, it makes a splash of the game which hangs for two seconds then exits out the bubble. Adrenaline works if I boot into it, only have this issue when trying to boot from launcher.

**Comment by gotbletu** [comment]
- did you solve this? the vita-launcher just start the adrenalinelauncher.vpk bubble but then kick me back out
- i tryed different driver options still, nothing works
- the games works fine if i open from Adrenaline directly
- i installed all the requirement i believe
https://github.com/cy33hc/vita-launcher/releases/download/v2.4/AdrenalineLauncher.vpk
https://github.com/cy33hc/vita-launcher/releases/download/v2.4/launcher.vpk
https://github.com/ONElua/AdrenalineBubbleManager/releases/download/6.13/AdrenalineBubbleManager.vpk

**Comment by cy33hc** [comment]
@gotbletu What version of Adrenaline do you have? 6.9 or v7. You will have to use AdernalineBubbleManager 6.12 if you have older adrenaline 6.9.

**Comment by gotbletu** [comment]
Got it Working now, thanks for the hint, think is because i had 2 Adrenaline version.
- older Adrenaline install on my ur0: on the PSTV
- newer Adrenaline v7 on my 2TB Hard Drive ux0: (via usbmc https://github.com/yifanlu/usbmc/releases/tag/v6)
- so i had to unplug the HDD, and just bootup the PSTV by itself without any memory card or hard drive and uninstall all the Bubble (Adrenaline, Vita-launcher,AdrenalineBubbleManager, AdrenalineLauncher)
- Then rebooted the PSTV with the Hard Drive plugged in again and just reinstalled everything below

1. install Adrenaline v7 https://github.com/TheOfficialFloW/Adrenaline/releases/download/v7/Adrenaline.vpk
2. open Adrenaline v7, downloaded the 661.PBP
3. open Adrenaline v7 again to populate the files and setup the time/date/user for the PSP
4. Installed https://github.com/cy33hc/vita-launcher/releases/download/v2.4/launcher.vpk
5. Started Vita-Launcher 2.4, it see all my games Vita/PSP/PSX/...etc
6. Installed https://github.com/cy33hc/vita-launcher/releases/download/v2.4/AdrenalineLauncher.vpk
7. Installed https://github.com/ONElua/AdrenalineBubbleManager/releases/download/6.13/AdrenalineBubbleManager.vpk
8. Started AdernalineBubbleManager 6.13, it said it installed the BubbleBooter plugin, and restarted the PSTV
9. Started Vita-Launcher 2.4, open a PSP game
